ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.mbops.online
CATALOGUE_HOST: catalogue-dev.mbops.online
REDIS_HOST: redis-dev.mbops.online
USER_HOST: user-dev.mbops.online
CART_HOST: cart-dev.mbops.online
MYSQL_HOST: mysql-dev.mbops.online
SHIPPING_HOST: shipping-dev.mbops.online
RABBITMQ_HOST: rabbitmq-dev.mbops.online
PAYMENT_HOST: payment-dev.mbops.online